package com.mlh.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_content", "id", Content.class);
		arp.addMapping("t_downloader_config", "id", DownloaderConfig.class);
		arp.addMapping("t_page_detail", "id", PageDetail.class);
		arp.addMapping("t_page_list", "id", PageList.class);
		arp.addMapping("price_product", "id", Product.class);
		arp.addMapping("ip", "id", IPList.class);
	}
}

