package com.mlh.model;

import com.mlh.model.base.BaseDemo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Demo extends BaseDemo<Demo> {
	public static final Demo dao = new Demo();
}
