package com.mlh.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.mlh.model.base.BaseDownloaderConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DownloaderConfig extends BaseDownloaderConfig<DownloaderConfig> {
	public static final DownloaderConfig dao = new DownloaderConfig();

	/**
	 * 
	 * @Description: 按状态查询信息
	 * @author liujiecheng
	 */
	public List<DownloaderConfig> findByStatus(String status) {
		return dao.find("select * from t_downloader_config where status = ? order by createTime asc", status);
	}
	
	public void updateStatusById(String status, String id) {
		Db.update("update t_downloader_config set status = ?, updateTime = now() where id = ?", status, id);
	}
}
