package com.mlh.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.mlh.model.base.BasePageList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PageList extends BasePageList<PageList> {
	public static final PageList dao = new PageList();

	/**
	 * 
	 * @Description: 批量保存
	 * @author liujiecheng
	 */
	public int[] saveAll(List<PageList> list) {
		return Db.batchSave(list, list.size());
	}

	/**
	 * 
	 * @Description: 按业务编码及状态查询信息
	 * @author liujiecheng
	 */
	public List<PageList> findByCodeAndStatus(String code, String status) {
		return dao.find("select * from t_page_list where code =? and handle = ? order by pageno asc", code, status);
	}
	
	/**
	 * 
	 * @Description: 更新当前列表页为已解释出详情页的路径
	 * @author liujiecheng
	 */
	public void updateHandleById(String handle, String id) {
		Db.update("update t_page_list set handle = ?, updateTime = now() where id = ?", handle, id);
	}
}
