package com.mlh.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.mlh.model.base.BaseProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Product extends BaseProduct<Product> {
	public static final Product dao = new Product();

	/**
	 * @Description: 批量保存
	 */
	public int[] saveProducts(List<Product> productList) {
		return Db.batchSave(productList, productList.size());
	}
	
    /**
     * @Description: 删除数据
     * @param id
     */
	public void deleteByCId(String id) {
		Db.update("delete from price_product where id = ?", id);
	}

}
