package com.mlh.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseImagesList<M extends BaseImagesList<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setPath(java.lang.String path) {
		set("path", path);
	}

	public java.lang.String getPath() {
		return get("path");
	}

	public void setDownload(java.lang.String download) {
		set("download", download);
	}

	public java.lang.String getDownload() {
		return get("download");
	}

	public void setUpload(java.lang.String upload) {
		set("upload", upload);
	}

	public java.lang.String getUpload() {
		return get("upload");
	}

	public void setFileKey(java.lang.String fileKey) {
		set("fileKey", fileKey);
	}

	public java.lang.String getFileKey() {
		return get("fileKey");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setDetailId(java.lang.String detailId) {
		set("detailId", detailId);
	}

	public java.lang.String getDetailId() {
		return get("detailId");
	}

	public void setSource(java.lang.String source) {
		set("source", source);
	}

	public java.lang.String getSource() {
		return get("source");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
