package com.mlh.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContent<M extends BaseContent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}
	
	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}

	public java.lang.String getCid() {
		return get("cid");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}


	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setSource(java.lang.String source) {
		set("source", source);
	}

	public java.lang.String getSource() {
		return get("source");
	}
	
	public void setDetailId(java.lang.String detailId) {
		set("detailId", detailId);
	}

	public java.lang.String getDetailId() {
		return get("detailId");
	}
	
	public void setMidiameter(java.lang.String midiameter) {
		set("midiameter", midiameter);
	}

	public java.lang.String getMidiameter() {
		return get("midiameter");
	}
	
	public void setHeight(java.lang.String height) {
		set("height", height);
	}

	public java.lang.String getHeight() {
		return get("height");
	}
	
	public void setCrown(java.lang.String crown) {
		set("crown", crown);
	}

	public java.lang.String getCrown() {
		return get("crown");
	}
	
	public void setGrounddiameter(java.lang.String grounddiameter) {
		set("grounddiameter", grounddiameter);
	}

	public java.lang.String getGrounddiameter() {
		return get("grounddiameter");
	}
	
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}
	
	public void setPrice(java.lang.String price) {
		set("price", price);
	}

	public java.lang.String getPrice() {
		return get("price");
	}
	
	public void setCompany(java.lang.String company) {
		set("company", company);
	}

	public java.lang.String getCompany() {
		return get("company");
	}
	
	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}
	
	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}
	
	public void setContacts(java.lang.String contacts) {
		set("contacts", contacts);
	}

	public java.lang.String getContacts() {
		return get("contacts");
	}
	
	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}
	
	public void setFax(java.lang.String fax) {
		set("fax", fax);
	}

	public java.lang.String getFax() {
		return get("fax");
	}
	
	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}
	
	public void setWebsite(java.lang.String website) {
		set("website", website);
	}

	public java.lang.String getWebsite() {
		return get("website");
	}
	
	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}
	
	public void setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
	}

	public java.lang.String getZipcode() {
		return get("zipcode");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}
	
	public void setReleasetime(java.util.Date releasetime) {
		set("releasetime", releasetime);
	}

	public java.util.Date getReleasetime() {
		return get("releasetime");
	}
}
